version: '3'

services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: cryptosignal
      POSTGRES_USER: cryptosignal

  app:
    image: crypto-signal
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - SETTINGS_SELECTED_TASK=simple_bot
      - SETTINGS_UPDATE_INTERVAL=180
      - DATABASE_ENGINE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=cryptosignal
      - DATABASE_PASSWORD=cryptosignal
    depends_on:
      - db

  reporter:
    image: crypto-signal
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - SETTINGS_SELECTED_TASK=reporter
      - SETTINGS_UPDATE_INTERVAL=120
      - DATABASE_ENGINE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=cryptosignal
      - DATABASE_PASSWORD=cryptosignal
    depends_on:
      - app
